name: paginator
description: A library for handling model data pagination.
version: 1.0.0
# homepage: https://www.example.com
repository: https://github.com/vaygeth89/dart_paginator_lib

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.5
  freezed: ^2.1.0
  
